name: Run Vitest

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - test/**
      - .github/workflows/test.yml

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    name: Run Vitest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Perform testing
        run: npm run coverage
